proxy:
  secretToken: <SENSITIVE>
singleuser:
  defaultUrl: "/lab"
  rbac:
    enabled: true
  serviceAccountName: [KUBE_SVC]
  image:
    name: snamburi3/gcloud-jupyter
    tag: latest
  extraEnv:
    SERVICE_ACCOUNT_NAME: "[GCP_SVC]@[PROJECT_ID].iam.gserviceaccount.com"
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
  uid: 0
  cmd: start-singleuser.sh
#    EDITOR: "vim"
  memory:
    limit: 1G
    guarantee: 1G
